name: CI

on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 'openjdk@1.8', 'openjdk@1.11' ]
        scala: [ '2.13.1', '2.12.10' ]

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
      with:
        java-version: ${{ matrix.java }}
    - name: run tests
      run: sbt ++${{ matrix.scala }} test

  publish:
    
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1        
      
      - name: check if git tag exists
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"

      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.8
        if: env.HEAD_TAG != ''
    
      - uses: olafurpg/setup-gpg@v2
        if: env.HEAD_TAG != ''

      - name: publish
        run: sbt ci-release
        if: env.HEAD_TAG != ''
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
